# Generated by Django 6.0.6 on 2026-06-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Member_class',
        ),
    ]
