# Generated by Django 6.0.6 on 2026-06-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_rename_member_member_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_class',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
