# Generated by Django 6.0.6 on 2026-06-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0004_member_class_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_class',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member_class',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
