# Generated by Django 4.2.30 on 2026-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_alter_member_class_joined_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_class',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
